apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: challengetemplates.infra.ctf.example.com
spec:
  group: infra.ctf.example.com
  scope: Namespaced
  names:
    plural: challengetemplates
    singular: challengetemplate
    kind: ChallengeTemplate
    shortNames:
      - ctmpl
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [image, resources]
              properties:
                image:
                  type: string
                resources:
                  type: object
                  properties:
                    cpu:
                      type: string
                      description: CPU request/limit (e.g., "500m")
                    memory:
                      type: string
                      description: Memory request/limit (e.g., "512Mi")
                networkProfile:
                  type: string
                  enum: ["isolated-egress-dns-only", "egress-allowlist", "open"]
                flagStrategy:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["hmac-per-instance", "static"]
                    envName:
                      type: string
                      default: "FLAG"
                    format:
                      type: string
                readinessProbe:
                  type: object
                  description: Pod readiness probe (subset of core/v1 Probe)
                  properties:
                    httpGet:
                      type: object
                      properties:
                        path: { type: string }
                        port:
                          oneOf:
                            - type: string
                            - type: integer
                    tcpSocket:
                      type: object
                      properties:
                        port:
                          oneOf:
                            - type: string
                            - type: integer
                    initialDelaySeconds: { type: integer }
                    periodSeconds: { type: integer }
                idleTimeoutMinutes:
                  type: integer
                  minimum: 5
                  default: 45
                envSchema:
                  type: object
                  additionalProperties: true
      subresources:
        status: {}