# Generated by Genie

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0004_roundtick"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160, unique=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["slug"], name="challenges_slug_idx")],
            },
        ),
        migrations.AddField(
            model_name="challenge",
            name="event",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="challenges", to="challenges.event"),
        ),
    ]