# Generated by Genie on demand

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_ratelimitconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="UiConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("challenge_list_layout", models.CharField(choices=[("list", "List"), ("grid", "Grid"), ("tabs", "Tabs (by category)"), ("cards", "Cards")], default="list", max_length=16)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]