# Generated by Genie on demand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_uiconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uiconfig",
            name="challenge_list_layout",
            field=models.CharField(
                max_length=32,
                choices=[
                    ("list", "List"),
                    ("grid", "Grid"),
                    ("tabs", "Tabs (by category)"),
                    ("cards", "Cards"),
                    ("masonry", "Masonry"),
                    ("grouped_tags", "Grouped by Tags"),
                    ("collapsible", "Collapsible Categories"),
                ],
                default="list",
            ),
        ),
        migrations.AddField(
            model_name="uiconfig",
            name="layout_by_category",
            field=models.JSONField(default=dict, blank=True),
        ),
    ]