# Generated by Genie on demand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_uiconfig_category_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="uiconfig",
            name="layout_by_tag",
            field=models.JSONField(default=dict, blank=True),
        ),
    ]