apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ctf.fullname" . }}-beat
  labels:
    app.kubernetes.io/name: {{ include "ctf.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ctf.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ctf.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: beat
    spec:
      containers:
        - name: beat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          command: ["celery"]
          args: ["-A", "ctfplatform", "beat", "--loglevel=info"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}