{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ctf.fullname" . }}-backend
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ctf.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: /api/metrics
      interval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
{{- end }}