name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "*" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Django checks
        working-directory: backend
        env:
          DJANGO_DEBUG: "1"
        run: |
          python manage.py check
          python - <<'PY'
          import os
          os.environ.setdefault("DJANGO_SETTINGS_MODULE","ctfplatform.settings")
          import django
          django.setup()
          from django.apps import apps
          print("Installed apps:", len(apps.get_app_configs()))
          PY